# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 22:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171019_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepo',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), null=True, size=None),
        ),
    ]
