# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 20:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_githubrepo_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubrepo',
            options={'verbose_name': 'repositório', 'verbose_name_plural': 'repositórios'},
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='language',
            field=models.CharField(max_length=100, verbose_name='linguagem'),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='name',
            field=models.CharField(max_length=250, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='repo_id',
            field=models.CharField(max_length=100, verbose_name='ID do repositório'),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
